### PR TITLE
broken original build progress

### PR DESCRIPTION
**Pull request by blackPantherOS**
Hi just a little build fix

### CODE REVIEW

**Comment by danpascu** [comment]
This is not how it should be fixed. The scripts should be stored executables in the repository. We are currently storing our repositories in darcs and just mirror them to github. The mirroring has an issue with correctly transferring the executable property of these scripts. I'll take a look at what can be done about that.

**Comment by pSub** [comment]
It seems that the executable bit is even missing in the darcs repository. Alt least with tag 3.1.1.

**Comment by altanai** [comment]
the patch on setup_pjsip.py works , Should be merged to master

**Comment by hasufell** [comment]
when will this be fixed??

**Comment by danpascu** [comment]
Fixed in the darcs-to-git conversion

**Pull request closed without merging**
