### PR TITLE
python3

### PR DESCRIPTION
**Pull request by jesusch**
the king is dead...long lives the king
"most" stuff seems good to me
but there are still issues with "upstream" packages that needs to be prepared for python3 (e.g. python-application)

### CODE REVIEW

**Comment by adigeo** [comment]
This is useless as running a 2to3 converter is by far not enough to convert the SDK code to be Python 3 compatible. You must convert first the dependencies to be Python 3 compatible and solve the broken ones that cannot just be ported without proper analysys and re-writing (e.g. multi-threading using green threads).

**Comment by JarbasAl** [comment]
is this on the roadmap at all? python2 reached its end of life

**Comment by adigeo** [comment]
Yes

**Comment by JarbasAl** [comment]
some context, i am making a skill for mycroft (see [here](https://github.com/JarbasSkills/skill--voip)) and ended up writting a wrapper around baresip (see [here](https://github.com/JarbasAl/baresipy)). I'd much rather have a native python implementation and this being python2 was the blocker for me

any ETA on python3 support? and is there anything i can do to help? I'd love to be notified once this is available, i am watching this thread, if theres somewere else i should subscribe for updates please let me know

Thank you!

**Comment by kethan1** [comment]
any update on this?? When will python3 support arrive?

**Comment by kethan1** [comment]
@adigeo any update on python3 support

**Comment by adigeo** [comment]
The current migration progress is logged here

https://sipsimpleclient.org/installation/

**Comment by adigeo** [comment]
The software has been migrated to Python 3

https://lists.ag-projects.com/pipermail/sipbeyondvoip/2021-February/003496.html

**Pull request closed without merging**
